export const site = {
  name: "Nikhil Shaw",
  jobTitle: "Client Solutions Manager",
  company: "Aisles & Shelves",
  url: "https://shawnikhil21.github.io/portfolio",
  title: "Nikhil Shaw | Client Solutions Manager, Aisles & Shelves",
  description:
    "Client Solutions Manager at Aisles & Shelves. On-ground retail merchandising, consumer sampling, rural activation, field operations, and client servicing.",
  keywords: [
    "Nikhil Shaw",
    "Client Solutions Manager",
    "Aisles & Shelves",
    "retail merchandising",
    "consumer sampling",
    "rural activation",
    "field operations",
    "field marketing",
    "client servicing",
    "client management",
    "marketing execution",
    "on-ground marketing",
    "trade marketing",
    "store visibility",
    "shelf presence",
    "route planning",
    "field team leadership",
    "process and reporting",
    "no-code reporting",
    "rural marketing",
    "retail execution",
    "PGDM Retail Management",
    "WeSchool Mumbai",
  ],
  knowsAbout: [
    "Retail merchandising",
    "Consumer sampling",
    "Rural activation",
    "Field operations",
    "Client servicing",
    "Marketing execution",
    "Field team leadership",
    "Process and reporting",
  ],
  ogImage: "https://shawnikhil21.github.io/portfolio/og-image.jpg",
  locale: "en_IN",
  linkedin:
    "https://www.linkedin.com/search/results/people/?keywords=Nikhil%20Shaw%20Client%20Solutions%20Manager%20Aisles%20Shelves",
} as const;
